### ISSUE TITLE
Deployment Overhaul wiki page

### ISSUE THREAD

**Issue by jtd-117** [WEHI-ResearchComputing/Genomics-Metadata-Multiplexing#5]
Need to draft a plan for how Marek Cmero's codebase will go from being deployed on AWS Elastic Beanstalk to WEHI's internal servers. This to prevent expenditure for AWS.

The following details need to be outlined
- [x] Deployment architecture
- [x] Instructions for Milton HPC deployment

**Comment by rNLKJA** [comment]
For " Instructions for Milton HPC deployment", we can inherent docs from imagining team after we dev the prototype :D

**Comment by rNLKJA** [comment]
[Instructions for Milton HPC deployment](https://github.com/WEHI-ResearchComputing/Genomics-Metadata-Multiplexing/wiki/Run-GMM-Application)
